<?php
get_header();
$apply_url = 'https://toolkit.mzizi.co.ke/portal/OnlineApplicationForm.aspx?q=d0d6b2f229d733c1e3156244805125a2';
?>
<main id="main-content" class="toolkit-page toolkit-apply-page">
	<section class="toolkit-apply-hero"><div><p class="toolkit-kicker">Toolkit admissions</p><h1>Start your course application</h1><p>Review the steps, choose your area of interest, then continue to the secure application portal.</p></div><span>Step 1 of 3</span></section>
	<nav class="toolkit-apply-steps" aria-label="Application steps"><span class="is-active"><b>1</b>Choose a course<small>Tell us your interest</small></span><span><b>2</b>Prepare documents<small>Have your details ready</small></span><span><b>3</b>Apply securely<small>Complete the portal form</small></span></nav>
	<section class="toolkit-apply-layout"><div class="toolkit-apply-card"><div class="toolkit-apply-card__heading"><i class="far fa-user"></i><div><h2>Choose your course</h2><p>Select an area to view the application route.</p></div></div><label for="toolkit-course-choice">Course interest</label><select id="toolkit-course-choice"><option value="Welding and Fabrication">Welding and Fabrication</option><option value="Renewable Energy">Renewable Energy</option><option value="Organic Farming Skills">Organic Farming Skills</option><option value="Digital Skills and Online Jobs">Digital Skills and Online Jobs</option><option value="Consultancy and Research">Consultancy and Research</option></select><div class="toolkit-apply-checklist"><h3>Before you continue</h3><ul><li><i class="fas fa-check"></i> Your full legal name and contact details</li><li><i class="fas fa-check"></i> Preferred course and intake information</li><li><i class="fas fa-check"></i> Supporting documents requested by admissions</li></ul></div><a class="toolkit-btn toolkit-btn--primary toolkit-apply-continue" href="<?php echo esc_url( $apply_url ); ?>" target="_blank" rel="noopener">Continue to secure application <i class="fas fa-arrow-right"></i></a></div><aside class="toolkit-apply-guide"><p class="toolkit-kicker">Course and field guide</p><h2 id="toolkit-course-title">Welding and Fabrication</h2><p id="toolkit-course-description">Gain modern metal joining and fabrication skills in workshop and industry settings.</p><div class="toolkit-apply-guide__meta"><span>Format <b>Hands-on learning</b></span><span>Support <b>Admissions guidance</b></span></div><h3>What happens next?</h3><ol><li>Complete the official online application.</li><li>Admissions reviews your details and any required documents.</li><li>Toolkit contacts you with the next steps for your selected programme.</li></ol><a href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Need application help? Contact admissions <i class="fas fa-arrow-right"></i></a></aside></section>
</main>
<?php get_footer();
