<?php
get_header();
$image = get_stylesheet_directory_uri() . '/assets/images/pages/contact.jpg';
?>
<main id="main-content" class="toolkit-page toolkit-contact-page">
	<section class="toolkit-contact-hero" style="background-image:url('<?php echo esc_url( $image ); ?>')"><div><p class="toolkit-kicker">Contact Toolkit</p><h1>Let’s start a useful conversation</h1><p>Contact Toolkit for clear guidance about courses, admissions, partnerships, or visiting The Toolkit for Skills and Innovation.</p></div></section>
	<section class="toolkit-contact-layout toolkit-section">
		<div class="toolkit-contact-details"><p class="toolkit-kicker">Get in touch</p><h2>How can we help?</h2><p>Choose the most direct route below or send a message through the form.</p><a href="tel:+254709549200"><i class="fas fa-phone-alt" aria-hidden="true"></i><span><small>Call us</small>+254 709 549 200</span></a><a href="https://wa.me/254711802855" target="_blank" rel="noopener noreferrer"><i class="fab fa-whatsapp" aria-hidden="true"></i><span><small>WhatsApp us</small>+254 711 802 855</span></a><a href="mailto:office@toolkitafrica.ac.ke"><i class="far fa-envelope" aria-hidden="true"></i><span><small>Email us</small>office@toolkitafrica.ac.ke</span></a><p class="toolkit-contact-address"><i class="fas fa-map-marker-alt" aria-hidden="true"></i><span><small>Visit us</small>The Toolkit for Skills and Innovation, Karen-Kikuyu Southern Bypass, Kikuyu, Kenya</span></p></div>
		<div class="toolkit-contact-form"><p class="toolkit-kicker">Send a message</p><h2>Tell us what you need</h2><?php echo do_shortcode( '[contact-form-7 id="10981" title="Contact form 1"]' ); ?></div>
	</section>
	<section class="toolkit-section toolkit-institutional-intro"><div><p class="toolkit-kicker">Admissions and partnerships</p><h2>Contact Toolkit with the right information</h2><p>For course enquiries, tell us which learning pathway interests you and whether you need guidance on entry requirements, schedules, fees, funding or the next intake. The admissions team can then give you current information before you submit an application.</p><p>If you are planning a visit, share your preferred date, the purpose of the visit and the number of people expected. Toolkit is located on the Karen-Kikuyu Southern Bypass in Kikuyu, Kenya. Calling ahead helps the team prepare for learners, partners, employers and other visitors.</p><p>Organisations can contact Toolkit about training partnerships, workforce research, learner support, industry exposure and job-linkage opportunities. Include a short description of your organisation and the outcome you want to explore so the enquiry reaches the right team. The <a href="<?php echo esc_url( home_url( '/about-toolkit-africa/' ) ); ?>">About Toolkit page</a> explains the institution’s training model and purpose.</p><p>For the fastest response, call or use WhatsApp during working hours. You can also review <a href="<?php echo esc_url( home_url( '/our-ventures/' ) ); ?>">current Toolkit courses</a>, begin a <a href="<?php echo esc_url( home_url( '/apply/' ) ); ?>">course application</a>, or check the <a href="<?php echo esc_url( home_url( '/notice-board/' ) ); ?>">Notice Board</a> before contacting us.</p></div><img src="<?php echo esc_url( $image ); ?>" width="760" height="520" loading="lazy" alt="Contact Toolkit for admissions and partnership enquiries"></section>
	<section class="toolkit-contact-map">
		<div class="toolkit-contact-location">
			<div><p class="toolkit-kicker">Visit Toolkit</p><h2>Find us in Kikuyu</h2><p>The Toolkit for Skills and Innovation, Karen-Kikuyu Southern Bypass, Kikuyu, Kenya.</p></div>
			<a class="toolkit-btn toolkit-btn--primary" href="https://www.google.com/maps/search/?api=1&amp;query=The%20Toolkit%20for%20Skills%20and%20Innovation%2C%20Kikuyu%2C%20Kenya" target="_blank" rel="noopener noreferrer">Open in Google Maps <i class="fas fa-external-link-alt" aria-hidden="true"></i></a>
		</div>
	</section>
</main>
<?php get_footer();
