<?php
require_once get_stylesheet_directory() . '/inc/course-catalog.php';
get_header();
$catalog   = eduma_child_course_catalog();
$is_2026   = eduma_child_2026_catalog_enabled();
$apply_url = home_url( '/apply/' );
$hero      = get_stylesheet_directory_uri() . '/assets/images/courses/electrical.jpg';
?>
<main id="main-content" class="toolkit-page toolkit-courses-page">
	<section class="toolkit-courses-hero" style="background-image:url('<?php echo esc_url( $hero ); ?>')"><div><p class="toolkit-kicker"><?php echo $is_2026 ? '2026 course catalog' : 'Toolkit learning pathways'; ?></p><h1>Practical skills courses in Kenya</h1><p><?php echo $is_2026 ? 'Explore practical skills courses in Kenya documented in Toolkit’s 2026 admissions prospectus. Admissions will confirm current availability and costs.' : 'Explore established practical skills courses in Kenya while the next admissions catalog is being prepared for release.'; ?></p><div class="toolkit-actions"><a class="toolkit-btn toolkit-btn--primary" href="<?php echo esc_url( $apply_url ); ?>">Apply now <i class="fas fa-arrow-right"></i></a><a class="toolkit-btn toolkit-btn--secondary" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Talk to admissions</a></div></div></section>
	<section class="toolkit-section toolkit-course-directory"><div class="toolkit-directory-heading"><div><p class="toolkit-kicker">Choose a pathway</p><h2><?php echo $is_2026 ? 'Compare practical skills courses' : 'Current practical programmes'; ?></h2></div><p>Compare each learning focus, then ask admissions to confirm programme availability, entry guidance, schedules and costs before enrolment. Toolkit courses connect applied learning with work, enterprise and recognised progression opportunities. Read <a href="<?php echo esc_url( home_url( '/about-toolkit-africa/' ) ); ?>">how Toolkit’s skills training model works</a>.</p></div><div class="toolkit-course-directory__grid"><?php foreach ( $catalog as $slug => $course ) : $course_url = isset( $course['url'] ) ? $course['url'] : home_url( '/courses/' . $slug . '/' ); ?><article><div class="toolkit-course-directory__image" style="background-image:url('<?php echo esc_url( $course['image'] ); ?>')"><i class="fas <?php echo esc_attr( $course['icon'] ); ?>"></i></div><div><h2><?php echo esc_html( $course['title'] ); ?></h2><p><?php echo esc_html( $course['short'] ); ?></p><ul><li><strong>Duration:</strong> <?php echo esc_html( $course['duration'] ); ?></li><li><strong>Intakes:</strong> <?php echo esc_html( $course['intakes'] ); ?></li></ul><a href="<?php echo esc_url( $course_url ); ?>">View programme <i class="fas fa-arrow-right"></i></a></div></article><?php endforeach; ?></div></section>
	<section class="toolkit-support"><i class="fas fa-comments"></i><div><h2>Not sure which pathway fits?</h2><p>Admissions can help compare entry requirements, schedules, fees, and funding options.</p></div><a class="toolkit-btn toolkit-btn--primary" href="<?php echo esc_url( $apply_url ); ?>">Apply now <i class="fas fa-arrow-right"></i></a></section>
</main>
<?php get_footer();
