<?php
get_header();
$image     = get_stylesheet_directory_uri() . '/assets/images/pages/welding.jpg';
$apply_url = 'https://toolkit.mzizi.co.ke/portal/OnlineApplicationForm.aspx?q=d0d6b2f229d733c1e3156244805125a2';
?>
<main id="main-content" class="toolkit-page toolkit-course-page">
	<div class="toolkit-breadcrumb"><a href="<?php echo esc_url( home_url( '/' ) ); ?>">Home</a><span>/</span><a href="<?php echo esc_url( home_url( '/our-ventures/' ) ); ?>">Our Courses</a><span>/</span><span>MIG/MAG Welding</span></div>
	<section class="toolkit-course-hero" style="background-image:url('<?php echo esc_url( $image ); ?>')">
		<div class="toolkit-course-hero__content">
			<p class="toolkit-kicker">Practical. Industry-relevant. Future-ready.</p>
			<h1>MIG/MAG<br>Welding</h1>
			<p>Build confidence in MIG/MAG welding through workshop practice, simulation, and instructor-led training in Kikuyu, Kenya.</p>
			<ul class="toolkit-course-facts" aria-label="Course facts"><li><i class="fas fa-clock"></i><span>Format<strong>Hands-on learning</strong></span></li><li><i class="fas fa-user-graduate"></i><span>Level<strong>Beginner to intermediate</strong></span></li><li><i class="fas fa-briefcase"></i><span>Outcome<strong>Career-ready skills</strong></span></li></ul>
		</div>
		<aside class="toolkit-course-panel"><h2>About this course</h2><details open><summary>Why learn with Toolkit?</summary><p>Practice with modern equipment and receive feedback from experienced instructors.</p></details><details><summary>Learning outcomes</summary><p>Develop safe workshop habits, MIG/MAG process control, welding technique, and quality awareness.</p></details><details><summary>Career options</summary><p>Explore pathways into welding, workshop operations, technical production, and self-employment.</p></details><details><summary>Frequently asked questions</summary><p>Contact admissions for current intakes, fees, entry requirements, and campus information.</p></details></aside>
		<div class="toolkit-course-hero__benefits"><span><i class="fas fa-tools"></i><b>Hands-on training</b>Workshop-led practice</span><span><i class="fas fa-industry"></i><b>Industry focus</b>Relevant technical skills</span><span><i class="fas fa-certificate"></i><b>Progress support</b>Guidance throughout learning</span><a href="<?php echo esc_url( $apply_url ); ?>" target="_blank" rel="noopener">Apply now <i class="fas fa-arrow-right"></i></a></div>
	</section>
	<section class="toolkit-section toolkit-learn"><div class="toolkit-section__heading"><p class="toolkit-kicker">Training focus</p><h2>What you will learn</h2></div><div class="toolkit-skill-grid"><article><i class="fas fa-shield-alt"></i><h3>Workshop safety</h3><p>Safe working practices and equipment care.</p></article><article><i class="fas fa-fire"></i><h3>MIG/MAG process setup</h3><p>Prepare equipment and settings for controlled welds.</p></article><article><i class="fas fa-tools"></i><h3>Torch control</h3><p>Practise positioning, travel, and consistent technique.</p></article><article><i class="fas fa-drafting-compass"></i><h3>Technical drawings</h3><p>Interpret drawings and job specifications.</p></article><article><i class="fas fa-check-circle"></i><h3>Weld quality</h3><p>Inspect work and identify areas for improvement.</p></article></div></section>
	<section class="toolkit-section toolkit-course-overview"><div><p class="toolkit-kicker">Course overview</p><h2>Skills that translate into opportunity.</h2><p>The Toolkit welding programme combines instructor-led theory, practical workshop time, and virtual-reality supported learning where appropriate. It is designed for learners who want a grounded start or a structured way to strengthen existing experience.</p><dl><div><dt>Delivery</dt><dd>Practical and instructor-led</dd></div><div><dt>Fees and intake</dt><dd>Confirmed by admissions</dd></div><div><dt>Application</dt><dd>Online admissions portal</dd></div></dl><div class="toolkit-actions"><a class="toolkit-btn toolkit-btn--primary" href="<?php echo esc_url( $apply_url ); ?>" target="_blank" rel="noopener">Apply now</a><a class="toolkit-btn toolkit-btn--secondary" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Contact admissions</a></div></div><figure><img src="<?php echo esc_url( $image ); ?>" alt="Learner using welding training equipment" loading="lazy"></figure></section>
	<section class="toolkit-support"><i class="fas fa-headset"></i><div><h2>Need help choosing a course?</h2><p>Admissions can guide you on the right pathway and current entry requirements.</p></div><a class="toolkit-btn toolkit-btn--secondary" href="<?php echo esc_url( home_url( '/contact/' ) ); ?>">Contact us <i class="fas fa-arrow-right"></i></a></section>
</main>
<?php get_footer();
